apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: postgresql
  labels:
    app: postgresql
type: Opaque
stringData:
  postgres-password: "postgres"  # ALTERE ESTA SENHA EM PRODUÇÃO!